#!/usr/bin/env python3
import tomllib  # Python 3.11+, else use `import tomli as tomllib`
from pathlib import Path
import sys

# Paths
alacritty_theme_path = Path.home() / ".config/omarchy/current/theme/alacritty.toml"
wezterm_theme_path = Path.home() / ".config/omarchy/current/theme/wezterm.lua"

def convert():
    with open(alacritty_theme_path, "rb") as f:
        data = tomllib.load(f)

    colors = data.get("colors", {})
    normal = colors.get("normal", {})
    bright = colors.get("bright", {})
    primary = colors.get("primary", {})
    cursor = colors.get("cursor", {})
    selection = colors.get("selection", {})

    # Build Lua config
    lua = f"""-- Autogenerated from {alacritty_theme_path}
return {{
  colors = {{
    foreground = "{primary.get("foreground", "#ffffff")}",
    background = "{primary.get("background", "#000000")}",
    cursor_bg = "{cursor.get("cursor", "#ffffff")}",
    cursor_border = "{cursor.get("cursor", "#ffffff")}",
    cursor_fg = "{cursor.get("text", "#000000")}",
    selection_bg = "{selection.get("background", "#555555")}",
    selection_fg = "{selection.get("text", "#ffffff")}",
    ansi = {{
      "{normal.get("black", "#000000")}", "{normal.get("red", "#ff0000")}",
      "{normal.get("green", "#00ff00")}", "{normal.get("yellow", "#ffff00")}",
      "{normal.get("blue", "#0000ff")}", "{normal.get("magenta", "#ff00ff")}",
      "{normal.get("cyan", "#00ffff")}", "{normal.get("white", "#ffffff")}",
    }},
    brights = {{
      "{bright.get("black", "#555555")}", "{bright.get("red", "#ff5555")}",
      "{bright.get("green", "#55ff55")}", "{bright.get("yellow", "#ffff55")}",
      "{bright.get("blue", "#5555ff")}", "{bright.get("magenta", "#ff55ff")}",
      "{bright.get("cyan", "#55ffff")}", "{bright.get("white", "#ffffff")}",
    }},
  }},
  window_padding = {{
    left = {data.get("window", {}).get("padding", {}).get("x", 0)},
    right = {data.get("window", {}).get("padding", {}).get("x", 0)},
    top = {data.get("window", {}).get("padding", {}).get("y", 0)},
    bottom = {data.get("window", {}).get("padding", {}).get("y", 0)},
  }},
}}
"""

    wezterm_theme_path.write_text(lua)
    print(f"✔ Wrote {wezterm_theme_path}")

if __name__ == "__main__":
    try:
        convert()
    except Exception as e:
        sys.exit(f"Error: {e}")

