#!/usr/bin/env python3
import tomllib  # Python 3.11+, else use `import tomli as tomllib`
from pathlib import Path
import sys

# Paths
alacritty_theme_path = Path.home() / ".config/omarchy/current/theme/alacritty.toml"
wezterm_theme_path = Path.home() / ".config/omarchy/current/theme/wezterm.lua"

def convert_color(color_str, primary_bg="#000000", primary_fg="#ffffff"):
    """Convert color values to WezTerm format"""
    if color_str == "CellBackground":
        return primary_bg
    elif color_str == "CellForeground":
        return primary_fg
    elif color_str.startswith("0x"):
        return "#" + color_str[2:]
    elif color_str.startswith("#"):
        return color_str
    else:
        # Assume it's already in the right format or handle as needed
        return color_str

def convert():
    with open(alacritty_theme_path, "rb") as f:
        data = tomllib.load(f)

    colors = data.get("colors", {})
    normal = colors.get("normal", {})
    bright = colors.get("bright", {})
    primary = colors.get("primary", {})
    cursor = colors.get("cursor", {})
    selection = colors.get("selection", {})

    # Get primary colors for CellBackground/CellForeground substitution
    primary_bg = convert_color(primary.get("background", "#000000"))
    primary_fg = convert_color(primary.get("foreground", "#ffffff"))

    # Build Lua config
    lua = f"""-- Autogenerated from {alacritty_theme_path}
return {{
  colors = {{
    foreground = "{primary_fg}",
    background = "{primary_bg}",
    cursor_bg = "{convert_color(cursor.get("cursor", "#ffffff"), primary_bg, primary_fg)}",
    cursor_border = "{convert_color(cursor.get("cursor", "#ffffff"), primary_bg, primary_fg)}",
    cursor_fg = "{convert_color(cursor.get("text", "#000000"), primary_bg, primary_fg)}",
    selection_bg = "{convert_color(selection.get("background", "#555555"), primary_bg, primary_fg)}",
    selection_fg = "{convert_color(selection.get("text", "#ffffff"), primary_bg, primary_fg)}",
    ansi = {{
      "{convert_color(normal.get("black", "#000000"), primary_bg, primary_fg)}", "{convert_color(normal.get("red", "#ff0000"), primary_bg, primary_fg)}",
      "{convert_color(normal.get("green", "#00ff00"), primary_bg, primary_fg)}", "{convert_color(normal.get("yellow", "#ffff00"), primary_bg, primary_fg)}",
      "{convert_color(normal.get("blue", "#0000ff"), primary_bg, primary_fg)}", "{convert_color(normal.get("magenta", "#ff00ff"), primary_bg, primary_fg)}",
      "{convert_color(normal.get("cyan", "#00ffff"), primary_bg, primary_fg)}", "{convert_color(normal.get("white", "#ffffff"), primary_bg, primary_fg)}",
    }},
    brights = {{
      "{convert_color(bright.get("black", "#555555"), primary_bg, primary_fg)}", "{convert_color(bright.get("red", "#ff5555"), primary_bg, primary_fg)}",
      "{convert_color(bright.get("green", "#55ff55"), primary_bg, primary_fg)}", "{convert_color(bright.get("yellow", "#ffff55"), primary_bg, primary_fg)}",
      "{convert_color(bright.get("blue", "#5555ff"), primary_bg, primary_fg)}", "{convert_color(bright.get("magenta", "#ff55ff"), primary_bg, primary_fg)}",
      "{convert_color(bright.get("cyan", "#55ffff"), primary_bg, primary_fg)}", "{convert_color(bright.get("white", "#ffffff"), primary_bg, primary_fg)}",
    }},
  }},
  window_padding = {{
    left = {data.get("window", {}).get("padding", {}).get("x", 0)},
    right = {data.get("window", {}).get("padding", {}).get("x", 0)},
    top = {data.get("window", {}).get("padding", {}).get("y", 0)},
    bottom = {data.get("window", {}).get("padding", {}).get("y", 0)},
  }},
}}
"""

    wezterm_theme_path.write_text(lua)
    print(f"✔ Wrote {wezterm_theme_path}")

if __name__ == "__main__":
    try:
        convert()
    except Exception as e:
        sys.exit(f"Error: {e}")
